# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 13:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import parler.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='adresse')),
                ('zip_Code', models.CharField(blank=True, max_length=5, null=True, verbose_name='code postal')),
                ('city', models.CharField(blank=True, max_length=75, null=True, verbose_name='ville')),
                ('website', models.CharField(blank=True, max_length=150, null=True, verbose_name='site web')),
                ('contact_Email', models.EmailField(blank=True, max_length=150, null=True, verbose_name='email contact')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=b'', verbose_name='avatar')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProfileTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('bio', models.TextField(max_length=1000, verbose_name='Bio')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translation', to='factures.Profile')),
            ],
            options={
                'managed': True,
                'db_table': 'factures_profile_translation',
                'db_tablespace': '',
                'default_permissions': (),
                'verbose_name': 'profile Translation',
            },
        ),
        migrations.AlterUniqueTogether(
            name='profiletranslation',
            unique_together=set([('language_code', 'master')]),
        ),
    ]
