# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 09:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0002_auto_20170619_1711'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name_plural': 'statuses'},
        ),
    ]
