# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0004_auto_20170623_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientname', models.CharField(blank=True, max_length=50, null=True, verbose_name='nom client')),
                ('clientaddress', models.CharField(blank=True, max_length=100, null=True, verbose_name='adresse client')),
                ('clientzipcode', models.CharField(blank=True, max_length=5, null=True, verbose_name='code postal client')),
            ],
        ),
    ]
