# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 12:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0005_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposition',
            name='proposition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='factures.Ligne'),
            preserve_default=False,
        ),
    ]
