# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0006_proposition_proposition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposition',
            name='proposition',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
