# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 09:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0007_auto_20170703_1529'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='clientaddress',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='clientname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='clientzipcode',
            new_name='zipcode',
        ),
    ]
