# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0008_auto_20170706_1120'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.AddField(
            model_name='proposition',
            name='date_creation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposition',
            name='date_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
